# Generated by Django 5.1.5 on 2025-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('POLICESTATION', 'policestation'), ('USER', 'user'), ('LABOUR', 'labour')], max_length=22, null=True),
        ),
    ]
