# Generated by Django 5.1.5 on 2025-01-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='receiver',
        ),
    ]
