# Generated by Django 5.1.5 on 2025-01-27 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_remove_feedback_receiver'),
        ('my_admin', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labourer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_issues', to='my_admin.labourdetails')),
            ],
        ),
    ]
