# Generated by Django 5.1.5 on 2025-01-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_personalissue'),
        ('my_admin', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalissue',
            name='labourer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_admin.labourdetails'),
        ),
    ]
