# Generated by Django 5.1.5 on 2025-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0004_alter_personalissue_labourer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalissue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalissue',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalissue',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
