# Generated by Django 5.1.5 on 2025-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_usercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('SOLVED', 'solved')], default='pending', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
