# Generated by Django 5.1.5 on 2025-01-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_alter_labourdetails_age'),
        ('public', '0003_usercomplaint_status_alter_usercomplaint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_admin.stationdetails'),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in progress', 'in progress'), ('resolved', 'resolved')], default='pending', max_length=40, null=True),
        ),
    ]
