# Generated by Django 5.1.5 on 2025-01-28 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_requestlabour'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlabour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlabour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
