# Generated by Django 5.1.5 on 2025-01-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0003_notification'),
        ('public', '0006_requestlabour_created_at_requestlabour_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('labour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_admin.labourdetails')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.userdetails')),
            ],
        ),
    ]
