# Generated by Django 5.1.5 on 2025-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourdetails',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
