# Generated by Django 5.1.5 on 2025-01-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_alter_labourdetails_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='my_admin.stationdetails')),
            ],
        ),
    ]
