# Generated by Django 5.1.5 on 2025-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_remove_stationdetails_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourdetails',
            name='skills',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
